### ISSUE TITLE
Error installing pocketsphinx package on Ubuntu 18.04

### ISSUE THREAD

**Issue by Ricardo-Dinucci** [openassistant/oa-core#11]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46786868/51795348-bf68c100-21c8-11e9-82cc-2525e4afc81f.png)

**To Reproduce**
1. sudo pip install -r requirements.txt

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshuashort** [comment]
Make sure you have `libasound2-dev` installed.

**Comment by joshuashort** [comment]
fwiw, the Python requirements can have system-specific dependencies that needs to be installed first.. usually it's a matter of figuring out which of the Python packages is having trouble and then looking for help with that dependency.

The error message will typically tell you what you need to know. If it's trying to compile something and can't find a header, odds are you're missing the development version of something.
