### ISSUE TITLE
No Module Named 'gi'

### ISSUE THREAD

**Issue by emeri1md** [openassistant/oa-core#24]
I installed OpenAssistant and tried running it.  This is from a clean Arch install.  Audio is working.

**To Reproduce**
Say "BOOT MIND"
ERROR sound [__init__.py:_in:20]: Error playing sound: No module named 'gi'

**Expected behavior**
Expected to hear R2D2

**Desktop (please complete the following information):**
 - OS: Arch Linux, fully updated
 - Version Latest as of 10/2/19

**Comment by joshuashort** [comment]
Can you try something like `sudo apt-get install python3-gi`, with whatever manager/package name Arch uses? Or maybe it's `python3-gobject`.

**Comment by emeri1md** [comment]
It was the second one you listed.  Had to install another library on top of that, but it's now working.  Thanks for the help.  Looks like I'll get to start playing with it now.
