### ISSUE TITLE
Weird voice reply And Difficulty to understand what is said.

### ISSUE THREAD

**Issue by SylvanoTombo** [openassistant/oa-core#26]
The voice reply is weird.i can even understand what it said
Difficulty to understand what is said. But google easily understands it..

How i can fix that? Thanks

**Comment by joshuashort** [comment]
Thanks for reaching out -- you're right, the voice reply is basically garbage.

Here's where you'd start: https://github.com/openassistant/oa-core/blob/8609478baa8404051326b48f47ba1e465ff52c17/oa/modules/voice/__init__.py

I'd be interested to hear how it goes.. the options are to swap in a new library or see if the current ones can be configured satisfactorily.

Also, this might be related to #19?

**Comment by SylvanoTombo** [comment]
Thanks for your reply, i'll check it out !

**Comment by joshuashort** [comment]
I wouldn't say this is 'fixed', but there are deeper issues.
