### ISSUE TITLE
Is this still being mantained?

### ISSUE THREAD

**Issue by czadikem** [openassistant/oa-core#27]
I was wondering if this is stil being mantained?  Also how would i add aiml to it?

Thanks

**Comment by joshuashort** [comment]
It's still around. PRs, Issues, etc are welcome.

It'd be challenging to add AIML, but if you're interested, there are a few places to start..

I'm not familiar with the ecosystem of AIML, but you'd probably need an AIML parser / thing for Python. You'd need some way to load all that AIML stuff into some kind of OA structure (probably as a module).

If you're this far, you're kind of beyond what is currently possible without some deeper changes.

**Comment by czadikem** [comment]
Yeah I would be intreasted.  Thanks

**Comment by NickLar59** [comment]
<https://pypi.org/project/python-aiml/>
python-aiml · PyPI<https://pypi.org/project/python-aiml/>

[cid:image001.png@01D5D1B6.CCE23ED0]
1.
python-aiml implements an interpreter for AIML, the Artificial Intelligence Markup Language developed by Dr. Richard Wallace of the A.L.I.C.E. Foundation.

**Comment by czadikem** [comment]
How would I add this in as a module?

**Comment by joshuashort** [comment]
It's pretty hacky, but here's the way:

* make a folder for your module in `./oa/modules`, something like `my-aiml-thing`, and make an empty file in that folder `__oa__.py` (e.g. https://github.com/openassistant/oa-core/tree/master/oa/modules)
* wire in the module: https://github.com/openassistant/oa-core/blob/8609478baa8404051326b48f47ba1e465ff52c17/oa/__main__.py#L29-L40

The project @NickLar59 linked seems like a good start for AIML (https://pypi.org/project/python-aiml/).

What are you trying to add?
