### ISSUE TITLE
problem with starting up

### ISSUE THREAD

**Issue by Thasimo1** [openassistant/oa-core#29]
when i start up the oa.exe program, it just shows: ear - Sending to part: stt 
and nothing else. it will repeat this thing even if
 i say something

![image](https://user-images.githubusercontent.com/23641264/77799645-8995c580-7075-11ea-80e1-6e3d66d41ae0.png)

**Comment by joshuashort** [comment]
That seems to be from the release bundle for Windows; it hasn't been updated in quite some time, and I'm not sure where it came from. There isn't a great fix for that, but it'd be nice to get some eyes on recent updates from Windows folks. I'm mostly testing on macOS and some flavor of Debian. 

So, what seems to be going on here is an issue with pocketsphinx (perhaps the version installed, perhaps it's missing). I can't say much past that, sorry. ☹️

It'd be nice to figure out how this distribution/bundling stuff works..

**Comment by joshuashort** [comment]
There are many potential problems when starting up.. this one is kind of a storm of issues.

Don't take this as a rejection or invalidation: this is an accessibility and packaging problem that should be fixed.
