### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by nellePoint** [openassistant/oa-core#40]
after saying "Boot Mind" i get the error: Error playing sound: No module named 'gi'

running on Ubuntu Linux 20.10, python 3.

**Comment by rezmed** [comment]
same thing on archlinux , python3 
try installing the package  " apt install  python3-gobject" 
and also "pip install pygobject "
it worked for me

**Comment by nellePoint** [comment]
> same thing on archlinux , python3
> try installing the package " apt install python3-gobject"
> and also "pip install pygobject "
> it worked for me

Sweet that worked.
