### ISSUE TITLE
Failed to download Windows version

### ISSUE THREAD

**Issue by bydariogamer** [openassistant/oa-core#41]
**Describe the bug**
The webpage to which you redirect the download for Windows fails (404 error):
```
Not Found

The requested URL /download/oa_0.21_windows.zip was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**To Reproduce**
https://openassistant.org/download/oa_0.21_windows.zip

**Desktop**
Windows 10

**Comment by Duviri** [comment]
The windows version is accessible if you go to  https://openassistant.org/download/install/ 
The link on the download page https://openassistant.org/wp/download/ needs to be updated 
![image](https://user-images.githubusercontent.com/60038008/107739057-4c2b3c80-6d08-11eb-9325-bfefddf1d901.png)
