### ISSUE TITLE
Assistant not here me or Speech not recognized

### ISSUE THREAD

**Issue by deysuman** [openassistant/oa-core#7]
I run assistant it show Speech not recognized and not recognized my any command.

**Comment by joshuashort** [comment]
I know we don’t have our issue templates up, but that’s almost no information to work with.

Which version are you running (Is it one of the platform distributions or source directly from the repo)? OS? Can you paste the command and log output up to trying to get it to recognize a command?

It could be that you don't have all the dependencies installed; or it could be your mic.

**Comment by deysuman** [comment]
I use your latest version and windows os.

**Comment by joshuashort** [comment]
Please, provide the logs from start until error appears.

**Comment by vavrek** [comment]
Same thing is happening on my end. Normal launch, listening, yet without recognition. 

`pocketsphinx_continuous -inmic yes` works.

**Comment by joshuashort** [comment]
Nobody wants to post logs? My guess right now is that it’s a loading race condition. Don’t make any sounds at all until the system fully loads.

**Comment by deysuman** [comment]
How many time i'm mute ? I think that is very big bug.
