### ISSUE TITLE
docker-py 1.9.0 has requirement

### ISSUE THREAD

**Issue by barkingbandicoot** [openassistant/oa-core#9]
Hi,

How do I resolve:
docker-py 1.9.0 has requirement backports.ssl_match_hostname>=3.5, but you'll have backports-ssl-match-hostname 3.4.0.2 which is incompatible.

After typing the command:
pip install keyboard sounddevice playsound requests pyttsx3 pocketsphinx psutil feedparser python-forecastio numpy

I get the following:

Collecting keyboard
  Downloading https://files.pythonhosted.org/packages/4f/e0/3addb693f9387268044c5268880777cad3cc2ac457789884cca8381b2f7a/keyboard-0.13.2-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 1.8MB/s 
Collecting sounddevice
  Downloading https://files.pythonhosted.org/packages/fb/5d/0e6cf5ce99b99e76a24b573b94f9009d9d2f5cd13a73825d7e681c9a7a96/sounddevice-0.3.11-py2.py3-none-any.whl
Collecting playsound
  Downloading https://files.pythonhosted.org/packages/f5/16/10d897b0a83fb4b05b03a63d7a2667ab75f857f67f7062fd447dd3f49bf7/playsound-1.2.2-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (2.9.1)
Collecting pyttsx3
  Downloading https://files.pythonhosted.org/packages/24/4e/580726c73272344d3e74b7aaffae55ff6b6450061fbecb8cc6e112531c02/pyttsx3-2.7.tar.gz
Collecting pocketsphinx
  Downloading https://files.pythonhosted.org/packages/cd/4a/adea55f189a81aed88efa0b0e1d25628e5ed22622ab9174bf696dd4f9474/pocketsphinx-0.1.15.tar.gz (29.1MB)
    100% |████████████████████████████████| 29.1MB 481kB/s 
Collecting psutil
  Downloading https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 3.8MB/s 
Collecting feedparser
  Using cached https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2
Collecting python-forecastio
  Downloading https://files.pythonhosted.org/packages/0e/57/e837a44254b7fdf99f3e98ef16ddcc4b429c5b148e8ed4fab4b46e7756ea/python-forecastio-1.4.0.tar.gz
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/6a/a9/c01a2d5f7b045f508c8cefef3b079fe8c413d05498ca0ae877cffa230564/numpy-1.14.5-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 1.1MB/s 
Collecting CFFI>=1.0 (from sounddevice)
  Downloading https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 4.5MB/s 
Collecting responses (from python-forecastio)
  Downloading https://files.pythonhosted.org/packages/d9/a2/1cf64651ca0837ea627fbf0455231611bec85dbb7a9ffe761365950cabe5/responses-0.9.0-py2.py3-none-any.whl
Collecting pycparser (from CFFI>=1.0->sounddevice)
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 3.3MB/s 
Requirement already satisfied: mock; python_version in "2.6, 2.7, 3.2" in /usr/lib/python2.7/dist-packages (from responses->python-forecastio) (1.3.0)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from responses->python-forecastio) (1.10.0)
Collecting cookies (from responses->python-forecastio)
  Downloading https://files.pythonhosted.org/packages/6a/60/557f84aa2db629e5124aa05408b975b1b5d0e1cec16cde0bfa06aae097d3/cookies-2.2.1-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 10.0MB/s 
Requirement already satisfied: funcsigs in /usr/lib/python2.7/dist-packages (from mock; python_version in "2.6, 2.7, 3.2"->responses->python-forecastio) (0.4)
Requirement already satisfied: pbr>=0.11 in /usr/lib/python2.7/dist-packages (from mock; python_version in "2.6, 2.7, 3.2"->responses->python-forecastio) (1.8.0)
Building wheels for collected packages: pyttsx3, pocketsphinx, psutil, feedparser, python-forecastio, pycparser
  Running setup.py bdist_wheel for pyttsx3 ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/a2/8a/fe/11112aca9c89142c3a404bc67ef3393a7ad530da26639a05d4
  Running setup.py bdist_wheel for pocketsphinx ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/52/fd/52/2f62c9a0036940cc0c89e58ee0b9d00fcf78243aeaf416265f
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/0a/61/aa/a6f8545fc2a5d4402e303832ed2ea02b046396049bc5f34008
  Running setup.py bdist_wheel for feedparser ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/8c/69/b7/f52763c41c5471df57703a0ef718a32a5e81ee35dcf6d4f97f
  Running setup.py bdist_wheel for python-forecastio ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/16/9b/2c/a02515345bc95b8a6f285c3f5dff77dcf1bb68b02bf8d5b534
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/anarcho/.cache/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46
Successfully built pyttsx3 pocketsphinx psutil feedparser python-forecastio pycparser
docker-py 1.9.0 has requirement backports.ssl_match_hostname>=3.5, but you'll have backports-ssl-match-hostname 3.4.0.2 which is incompatible.
Installing collected packages: keyboard, pycparser, CFFI, sounddevice, playsound, pyttsx3, pocketsphinx, psutil, feedparser, cookies, responses, python-forecastio, numpy
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/f2py'
Consider using the `--user` option or check the permissions. 

Distro = KDE Neon User Edition
Thanks!

**Comment by joshuashort** [comment]
Not sure about the dependency issue, but it looks like you might also have a permissions issue?

**Comment by barkingbandicoot** [comment]
So, I was able to resolve the dependencies with a file from:
https://packages.debian.org/sid/all/python-backports.ssl-match-hostname/download

Now however I am not able to run it.
oa.py does not seem to exist in the open assistant github files I downloaded! ??
Thanks.

**Comment by joshuashort** [comment]
@barkingbandicoot -- we had a bit of an issue with a merge happening before it was ready. Use `__main__.py` instead of `oa.py`; that's the new launcher script location

**Comment by barkingbandicoot** [comment]
Ok - am I doing this wrong?

anarcho@KDENeon:~/Downloads/oa-core-master$ sudo python __main__.py
[sudo] password for anarcho: 
Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
    from core import oa, queue, Core, load_module
  File "/home/anarcho/Downloads/oa-core-master/core/__init__.py", line 88
    yield from self.__dict__
             ^
SyntaxError: invalid syntax

**Comment by joshuashort** [comment]
Don’t run it with sudo, and it requires Python3.

**Comment by barkingbandicoot** [comment]
Hi joshuashort,

Still nothing happening for me. I think I will leave it there. It is all a bit beyond my skill level thanks for your help nonetheless!
much appreciated!
anarcho@KDENeon:~/Downloads/oa-core-master$ python /home/anarcho/Downloads/oa-core-master/__main__.py 
Traceback (most recent call last):
  File "/home/anarcho/Downloads/oa-core-master/__main__.py", line 10, in <module>
    from core import oa, queue, Core, load_module
  File "/home/anarcho/Downloads/oa-core-master/core/__init__.py", line 88
    yield from self.__dict__
             ^
SyntaxError: invalid syntax


anarcho@KDENeon:~/Downloads/oa-core-master$ python3 /home/anarcho/Downloads/oa-core-master/__main__.py 
Traceback (most recent call last):
  File "/home/anarcho/Downloads/oa-core-master/__main__.py", line 10, in <module>
    from core import oa, queue, Core, load_module
  File "/home/anarcho/Downloads/oa-core-master/core/__init__.py", line 10, in <module>
    import psutil
ImportError: No module named 'psutil'

I get this when I run _main_.py in konsole:


Warning: Could not start program '/home/anarcho/Downloads/oa-core-master/__main__.py' with arguments '/home/anarcho/Downloads/oa-core-master/__main__.py'.



Warning: execve: Exec format error

**Comment by joshuashort** [comment]
Looks like you were close -- `psutil` must be an unlisted dependency. Install it with something like `pip3 install psutil`; may need to repeat for other "no module named" errors.
